torchrun --nproc_per_node=auto --master-port=29507 st_trainer_ddp_hf.py \
    --model_name "nasa-impact/indus-sde-st-v0.2" \
    --num_train_epochs 1 \
    --batch_size 64 \
    --gradient_accumulation_steps 6 \
    --lr 4e-5 \
    --eval_and_save_steps 500 \
    --output_base "../training_output" \
    --max_datapoints_per_src_for_eval 1000 \
    --warmup_ratio 0.02 \
    --cosine_cycle_steps_custom 2000 \
    --wb_project "nasa-indus-sde-s2" \
    --bat